package com.example.hnTea.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.hnTea.mvpmodel.greendaobean.PartnerNewsList;

import com.example.hnTea.db.PartnerNewsListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig partnerNewsListDaoConfig;

    private final PartnerNewsListDao partnerNewsListDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        partnerNewsListDaoConfig = daoConfigMap.get(PartnerNewsListDao.class).clone();
        partnerNewsListDaoConfig.initIdentityScope(type);

        partnerNewsListDao = new PartnerNewsListDao(partnerNewsListDaoConfig, this);

        registerDao(PartnerNewsList.class, partnerNewsListDao);
    }
    
    public void clear() {
        partnerNewsListDaoConfig.clearIdentityScope();
    }

    public PartnerNewsListDao getPartnerNewsListDao() {
        return partnerNewsListDao;
    }

}
